/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'signaciu' at '27.04.17 19:06' with Gradle 3.2.1
 *
 * @author signaciu, @date 27.04.17 19:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
